_target_: wrappers.AmplitudeMLPWrapper

net:
  _target_: models.mup_mlp.MuMLP

  n_features: 0   # overwritten once the data is loaded
  hidden_channels: 512
  hidden_layers: 5
  out_shape: 4
  loss: "MSE"
  gain: 1
  init_bias: true
  dropout_prob: 0
  batchnorm: false 
  BN_eps: 1e-5 #default PyTorch value
  BN_momentum: 0.1 #default PyTorch value

  activation: "gelu"
  num_groups: 1