executable            = /afs/cern.ch/user/j/joiturri/likelihoods/1908_2k_hn_5_hl.sh
arguments             = $(ClusterId) $(ProcId)
output                = /afs/cern.ch/user/j/joiturri/likelihoods/output/1908_2k_hn_5_hl_$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/user/j/joiturri/likelihoods/error/1908_2k_hn_5_hl_$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/user/j/joiturri/likelihoods/log/1908_2k_hn_5_hl_$(ClusterId).$(ProcId).log
request_gpus          = 1
+JobFlavour           = "testmatch"
queue